apiVersion: apps/v1
kind: Deployment
metadata:
  name: deletetask
spec: 
  replicas: 2
  selector:
    matchLabels:
      apps: deletetask
  template:
    metadata:
      labels:
        apps: deletetask
    spec:
      containers:
        - name: deletetask
          image: appsacrrrrrr.azurecr.io/appsdeletetask-ui:v1
          ports:
            - containerPort: 8000
          env: 
            - name: ConnectionString
              value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:appsserver.database.windows.net,1433;Database=appsdbb;Uid=devops123456;Pwd=devops@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

